### ISSUE TITLE
Issue trying to load EOD datasets 

### ISSUE THREAD

**Issue by csc5a2g** [CMEGroup/datamine_python#21]
Hi,

I'm trying to pull my EOD datasets from CME Datamine for saving locally and I plan to upload them into MS SQL Server. I've worked through your example (amending to account for EOD) and it get as far as ther data being downloaded but then I get an error:

----------------------------------------------------------------------------
 myDatamine.load_dataset('EOD', True)
downloading EOD data: 100%|██████████| 1820/1820 [03:43<00:00,  8.15it/s]
Traceback (most recent call last):

  File "<ipython-input-15-c02dac5b44bd>", line 1, in <module>
    myDatamine.load_dataset('EOD', True)

  File "C:\Anaconda3\lib\site-packages\datamine\io.py", line 252, in load_dataset
    return Loader.by_name(dataset).load(path, limit=limit)

  File "C:\Anaconda3\lib\site-packages\datamine\loaders\base.py", line 50, in by_name
    raise RuntimeError('Dataset not found: {}'.format(dataset))

RuntimeError: Dataset not found: EOD
----------------------------------------------------------------------------

What am I missing ?

Thanks
A

**Comment by csc5a2g** [comment]
Just dug into the code and saw that EOD datasets aren't support just yet.

**Comment by hamzaamjad** [comment]
@csc5a2g ,

Thank you for bringing this to our attention. There is a helper function which should allow you to get EOD data into a DataFrame.

A script could look like the following:

```Python
import datamine.io as dm # CME Github - Datamine Python
import pandas as pd

# Please enter your API credentials here
username = 'YOUR_USERNAME' # Starts with API_
password = 'YOUR_PASSWORD'

# Initialize Datamine Object
myDatamine = dm.DatamineCon(username = username, password = password, path = './data/')
myDatamine.processes = 4 # Parallel processing

# Get Data Catalog. Stored in myDatamine.data_catalog
myDatamine.get_catalog("EOD", limit = 100)

# Function downloads files, then loads into DataFrame. References myDatamine.data_catalog
# DataFrame is stored in myDatamine.eod_DF
myDatamine.eod_load()

# Basic information on End of Day DataFrame
myDatamine.eod_DF.shape
myDatamine.eod_DF.dtypes

# First record in End of Day DataFrame
myDatamine.eod_DF.iloc[0,:]
```

Let me know if you have any further questions -- I can additionally be reached at hamza.amjad@cmegroup.com.
