### ISSUE TITLE
trade_date and strike_price wrongly formatted 

### ISSUE THREAD

**Issue by V-kik** [CMEGroup/datamine_python#22]
Hi,

I just installed datamine_python and downloaded Time and Sales data on crude oil (CL and LO). 
It seems that the field trade_date and strike_price are wrongly formatted.
The strike is 3550 where it should be 35.50 and the trade_date always starts in 1970 although these trades are from yesterday.

Cheers,
Viktor

![Capture](https://user-images.githubusercontent.com/20340349/73443286-b15afc80-4356-11ea-8740-5b6c598eb5cd.PNG)

**Comment by hamzaamjad** [comment]
Viktor,

Thank you for bringing this to our attention. The following adjustments have been made to the loader file:

`trade_date` typing incorrectly -- now types to proper datetime format
`entry_date` was not typed as date -- now typed as datetime

Please reference the following screenshot, which refers to the same record as you identified:
![image](https://user-images.githubusercontent.com/22208079/74368989-a1a1d600-4da2-11ea-93d5-207fae6ce449.png)


Note that the `strike_price` format is correct -- both `strike_price & `trade_price` are treated as `float`. `strike_price` format is in spec with Globex.
